spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/reservation_db
    username: reservation_user
    password: reservation_password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db-changelog-master.xml
    enabled: true
    drop-first: true

logging:
  level:
    com.linkz: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
