package com.linkz.reservation.audit;

public enum AuditEventType {
    RESERVATION_CREATED,
    RESERVATION_CONFIRMED,
    RESERVATION_EXPIRED,
    PAYMENT_INITIATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    WEBHOOK_PAYMENT_SUCCESS_RECEIVED,
    WEBHOOK_PAYMENT_FAILURE_RECEIVED
}

